/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package recommender

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
	"k8s.io/klog/v2"
)

// LocateOutputDirectory finds the latest output directory generated by aiconfigurator
func LocateOutputDirectory(config *TaskConfig) (string, error) {
	// Build the directory prefix pattern
	prefix := fmt.Sprintf("%s_isl%d_osl%d_ttft%s_tpot%s_",
		config.ModelName,
		config.ISL,
		config.OSL,
		formatFloat(config.TTFT),
		formatFloat(config.TPOT),
	)

	klog.V(2).Infof("Looking for directories with prefix: %s", prefix)

	// Read save directory
	entries, err := os.ReadDir(config.SaveDir)
	if err != nil {
		return "", fmt.Errorf("failed to read save directory %s: %w", config.SaveDir, err)
	}

	// Find matching directories
	var matchingDirs []string
	for _, entry := range entries {
		if entry.IsDir() && strings.HasPrefix(entry.Name(), prefix) {
			fullPath := filepath.Join(config.SaveDir, entry.Name())
			matchingDirs = append(matchingDirs, fullPath)
		}
	}

	if len(matchingDirs) == 0 {
		return "", fmt.Errorf("no output directory found matching pattern: %s*\nPlease check if aiconfigurator executed successfully", prefix)
	}

	// Sort by modification time (most recent first)
	sort.Slice(matchingDirs, func(i, j int) bool {
		infoI, errI := os.Stat(matchingDirs[i])
		infoJ, errJ := os.Stat(matchingDirs[j])
		if errI != nil || errJ != nil {
			return false
		}
		return infoI.ModTime().After(infoJ.ModTime())
	})

	latestDir := matchingDirs[0]
	klog.V(2).Infof("Found latest output directory: %s", latestDir)

	// Verify directory structure
	aggDir := filepath.Join(latestDir, "agg")
	disaggDir := filepath.Join(latestDir, "disagg")

	if !dirExists(aggDir) || !dirExists(disaggDir) {
		return "", fmt.Errorf("output directory %s is missing required subdirectories (agg/disagg)", latestDir)
	}

	return latestDir, nil
}

// ParseGeneratorConfigs parses both agg and disagg generator configurations
func ParseGeneratorConfigs(outputDir string) (aggConfig, disaggConfig *GeneratorConfig, err error) {
	// Parse aggregation mode config
	aggConfigPath := filepath.Join(outputDir, "agg", "top1", "generator_config.yaml")
	aggConfig, err = parseGeneratorConfig(aggConfigPath)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse aggregation config: %w", err)
	}

	// Parse disaggregation mode config
	disaggConfigPath := filepath.Join(outputDir, "disagg", "top1", "generator_config.yaml")
	disaggConfig, err = parseGeneratorConfig(disaggConfigPath)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse disaggregation config: %w", err)
	}

	return aggConfig, disaggConfig, nil
}

// parseGeneratorConfig reads and parses a generator_config.yaml file
func parseGeneratorConfig(configPath string) (*GeneratorConfig, error) {
	klog.V(2).Infof("Parsing generator config from: %s", configPath)

	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file %s: %w", configPath, err)
	}

	var config GeneratorConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to unmarshal YAML from %s: %w", configPath, err)
	}

	// Validate required fields
	if config.K8s.Mode == "" {
		return nil, fmt.Errorf("config missing required field: k8s.mode")
	}

	klog.V(2).Infof("Successfully parsed %s mode config", config.K8s.Mode)
	return &config, nil
}

// formatFloat formats a float value for directory name matching
func formatFloat(f float64) string {
	// Remove trailing zeros and decimal point if not needed
	s := strconv.FormatFloat(f, 'f', -1, 64)
	// Convert to int string if it's a whole number
	if strings.Contains(s, ".") {
		s = strings.TrimRight(s, "0")
		s = strings.TrimRight(s, ".")
	}
	return s
}

// dirExists checks if a directory exists
func dirExists(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}
