
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: dynamo-agg
  namespace: None
spec:
  services:
    Frontend:
      dynamoNamespace: dynamo-agg
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
          imagePullPolicy: IfNotPresent

    SGLangWorker:
      dynamoNamespace: dynamo-agg
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
          workingDir: /workspace/components/backends/sglang
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-c"]
          args:
            - |
              set -euo pipefail
              args=(
                --model-path "QWEN3_32B"
                --served-model-name "QWEN3_32B"
                --tensor-parallel-size "1" --pipeline-parallel-size "1" --data-parallel-size "1" --kv-cache-dtype "fp8_e5m2" --max-running-requests "5" --expert-parallel-size "1" --moe-dense-tp-size "1" --cuda-graph-bs 1 2 3 4 5
              )
              exec python3 -m dynamo.sglang "${args[@]}"
