apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
    name: qwen3-32b-sglang-agg
spec:
    roles:
        - name: worker
          replicas: 1
          template:
            spec:
                containers:
                    - command:
                        - sh
                        - -c
                        - python3 -m sglang.launch_server --model-path /models/QWEN3_32B/ --enable-metrics --port 8000 --host 0.0.0.0 --tp-size 4
                      env:
                        - name: POD_IP
                          valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
                      imagePullPolicy: Always
                      name: sglang-worker
                      ports:
                        - containerPort: 8000
                      readinessProbe:
                        initialDelaySeconds: 30
                        periodSeconds: 10
                        tcpSocket:
                            port: 8000
                      resources:
                        limits:
                            cpu: "32"
                            memory: 29Gi
                            nvidia.com/gpu: "4"
                        requests:
                            cpu: "32"
                            memory: 29Gi
                            nvidia.com/gpu: "4"
                      volumeMounts:
                        - mountPath: /models/
                          name: model
                        - mountPath: /dev/shm
                          name: shm
                volumes:
                    - name: model
                      persistentVolumeClaim:
                        claimName: llm-model
                    - emptyDir:
                        medium: Memory
                        sizeLimit: 128Gi
                      name: shm
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: qwen3-32b-sglang-agg
    name: qwen3-32b-sglang-agg
    namespace: default
spec:
    ports:
        - name: http
          port: 8000
          protocol: TCP
          targetPort: 8000
    selector:
        rolebasedgroup.workloads.x-k8s.io/name: qwen3-32b-sglang-agg
        rolebasedgroup.workloads.x-k8s.io/role: worker
    type: ClusterIP
