
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: dynamo-disagg
  namespace: None
spec:
  services:
    Frontend:
      dynamoNamespace: dynamo-disagg
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
          imagePullPolicy: IfNotPresent

    SGLangPrefillWorker:
      dynamoNamespace: dynamo-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: prefill
      replicas: 2
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
          workingDir: /workspace/components/backends/sglang
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-c"]
          args:
            - |
              set -euo pipefail
              args=(
                --model-path "QWEN3_32B"
                --served-model-name "QWEN3_32B"
                --tensor-parallel-size "1" --pipeline-parallel-size "1" --data-parallel-size "1" --kv-cache-dtype "fp8_e5m2" --max-running-requests "1" --expert-parallel-size "1" --moe-dense-tp-size "1" --cuda-graph-bs 1
              )
              args+=(--host "0.0.0.0")
              args+=(--disaggregation-mode prefill)
              exec python3 -m dynamo.sglang "${args[@]}"
    SGLangDecodeWorker:
      dynamoNamespace: dynamo-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      subComponentType: decode
      replicas: 3
      resources:
        limits:
          gpu: "2"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
          workingDir: /workspace/components/backends/sglang
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash","-c"]
          args:
            - |
              set -euo pipefail
              args=(
                --model-path "QWEN3_32B"
                --served-model-name "QWEN3_32B"
                --tensor-parallel-size "2" --pipeline-parallel-size "1" --data-parallel-size "1" --kv-cache-dtype "fp8_e5m2" --max-running-requests "14" --expert-parallel-size "1" --moe-dense-tp-size "1" --cuda-graph-bs 1 2 3 4 5 6 7 8 9 10 11 12 13 14
              )
              args+=(--host "0.0.0.0")
              args+=(--disaggregation-mode decode)
              exec python3 -m dynamo.sglang "${args[@]}"
