apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: volcano-gang
spec:
  podGroupPolicy:
    # using volcano for gang-scheduling
    volcanoScheduling:
      queue: default
  roles:
    - name: role-sts
      replicas: 1
      template:
        spec:
          schedulerName: volcano
          containers:
            - name: sts
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
              ports:
                - containerPort: 80
              resources:
                requests:
                  nvidia.com/gpu: "1"
                limits:
                  nvidia.com/gpu: "1"

    - name: role-deploy
      replicas: 1
      workload:
        apiVersion: apps/v1
        kind: Deployment
      template:
        spec:
          schedulerName: volcano
          containers:
            - name: deploy
              image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
              ports:
                - containerPort: 80
              resources:
                requests:
                  nvidia.com/gpu: "1"
                limits:
                  nvidia.com/gpu: "1"
